/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#ifndef SOLVER_QPOASES_H
#define SOLVER_QPOASES_H

#include <stdio.h>
#include <math.h>


#define QPOASES_NVMAX      80
#define QPOASES_NCMAX      180
#define QPOASES_NWSRMAX    780
#define QPOASES_PRINTLEVEL PL_NONE
#define QPOASES_EPS        2.221e-16

typedef double real_t;

typedef struct Params_t {
/* Matrix of size: 80 x 80 (row major format) */
real_t H[ 6400 ];

/* Matrix of size: 180 x 80 (row major format) */
real_t A[ 14400 ];

/* Row vector of size: 80 */
real_t g[ 80 ];

/* Row vector of size: 80 */
real_t lb[ 80 ];

/* Row vector of size: 80 */
real_t ub[ 80 ];

/* Row vector of size: 180 */
real_t lbA[ 180 ];

/* Row vector of size: 180 */
real_t ubA[ 180 ];

} Params;

typedef struct Vars_t {
/* Row vector of size: 80 */
real_t x[ 80 ];

/* Row vector of size: 260 */
real_t y[ 260 ];

} Vars;

extern Params params;
extern Vars vars;

long solve(void);

#endif
