/*
 ******************************************************************************
 ***** EMBOCON MODEL INTERFACE ************************************************
 ******************************************************************************
 * EMBOCON_ModelInterface.c
 *
 *  Created on: 10.10.2011
 *      Author: schoppmeyerc
 *      E-Mail: christian.schoppmeyer@bci.tu-dortmund.de
 *      Version: 1.0
 ******************************************************************************
 * The Model Interface of the software platform defines common functions
 * for a system model and optimization problem in C code. Usually, the C
 * code is generated by the Modelica-Optimica-based online part of the
 * platform, but any other set of functions that implement the proper
 * semantics can be used as well. The Model Interface connects the C code
 * representation with an optimizer and an observer and offers both to
 * receive information of the model via calling the defined functions. The
 * Model Interface can be used to connect the same C code representation
 * to both the optimizer and the observer or two different C code
 * representations, one to the optimizer and one to the observer. The Model
 * Interface is not used for the connection between a system model and an
 * optimizer generated by the direct path by-pass; here the information
 * about the system and the optimization problem at hand is incorporated
 * in the optimizer leading to a better performance and resulting in a
 * combined callable C code representation.
 ******************************************************************************
 */

#include "EMBOCON_ModelInterface.h"


