/* Generated by S-function Builder */
#ifndef _SGEMS_SFUNC_BUS_H_
#define _SGEMS_SFUNC_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_xref_bus_
#define _DEFINED_TYPEDEF_FOR_xref_bus_ 
typedef struct {
  real_T x_C;
  real_T x_L;
  real_T v_C;
  real_T v_L;
  real_T theta;
  real_T omega;
  real_T u_C;
  real_T u_L;
} xref_bus;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_x_bus_
#define _DEFINED_TYPEDEF_FOR_x_bus_ 
typedef struct {
  real_T x_C;
  real_T x_L;
  real_T v_C;
  real_T v_L;
  real_T theta;
  real_T omega;
  real_T u_C;
  real_T u_L;
} x_bus;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_u_bus_
#define _DEFINED_TYPEDEF_FOR_u_bus_ 
typedef struct {
  real_T u_CR;
  real_T u_LR;
} u_bus;
#endif

/* Read only - ENDS */


#endif
