/* Generated by S-function Builder */
#ifndef _SGEMS_SFUNC_BUS_H_
#define _SGEMS_SFUNC_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"


#ifndef _DEFINED_TYPEDEF_FOR_x_bus_
#define _DEFINED_TYPEDEF_FOR_x_bus_ 
typedef struct {
  real_T x;
  real_T y;
  real_T z;
  real_T dx;
  real_T dy;
  real_T dz;
  real_T e11;
  real_T e12;
  real_T e13;
  real_T e21;
  real_T e22;
  real_T e23;
  real_T e31;
  real_T e32;
  real_T e33;
  real_T w1;
  real_T w2;
  real_T w3;
  real_T r;
  real_T dr;
  real_T delta;
  real_T ddelta;
} x_bus;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_u_bus_
#define _DEFINED_TYPEDEF_FOR_u_bus_ 
typedef struct {
  real_T dddelta;
  real_T ddr;
  real_T ur;
  real_T up;
} u_bus;
#endif

/* Read only - ENDS */


#endif
