/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#ifndef SOLVER_QPOASES_H
#define SOLVER_QPOASES_H

#include <stdio.h>
#include <math.h>


#define QPOASES_NVMAX      50
#define QPOASES_NCMAX      50
#define QPOASES_NWSRMAX    300
#define QPOASES_PRINTLEVEL PL_NONE
#define QPOASES_EPS        2.221e-16

typedef double real_t;

typedef struct Params_t {
/* Matrix of size: 50 x 50 (row major format) */
real_t H[ 2500 ];

/* Matrix of size: 50 x 50 (row major format) */
real_t A[ 2500 ];

/* Vector of size: 50 */
real_t g[ 50 ];

/* Vector of size: 50 */
real_t lb[ 50 ];

/* Vector of size: 50 */
real_t ub[ 50 ];

/* Vector of size: 50 */
real_t lbA[ 50 ];

/* Vector of size: 50 */
real_t ubA[ 50 ];

} Params;

typedef struct Vars_t {
/* Vector of size: 50 */
real_t x[ 50 ];

/* Vector of size: 100 */
real_t y[ 100 ];

} Vars;

extern Params params;
extern Vars vars;

long solve(void);

#endif
