/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/time.h>

#ifndef ACADO_H
#define ACADO_H

typedef double real_t;


/* COMMON DEFINITIONS:              */
/* -------------------------------- */




/* Number of control intervals */
#define ACADO_N   1
/* Number of differential states */
#define ACADO_NX  22
/* Number of differential state derivatives */
#define ACADO_NDX  0
/* Number of algebraic states */
#define ACADO_NXA  0
/* Number of controls */
#define ACADO_NU  4
/* Number of parameters */
#define ACADO_NP  0
/* Number of output functions */
#define NUM_OUTPUTS  0


/* GLOBAL VARIABLES:                */
/* -------------------------------- */
typedef struct ACADOvariables_ {
int resetIntegrator;


} ACADOvariables;


/* GLOBAL WORKSPACE:                */
/* -------------------------------- */
typedef struct ACADOworkspace_ {
real_t rk_dim44_swap;

/* Row vector of size: 44 */
int rk_dim44_perm[ 44 ];

/* Row vector of size: 44 */
real_t rk_dim44_bPerm[ 44 ];

/* Row vector of size: 10276 */
real_t acado_aux[ 10276 ];

real_t rk_ttt;

/* Column vector of size: 26 */
real_t rk_xxx[ 26 ];

/* Matrix of size: 2 x 22 (row major format) */
real_t rk_kkk[ 44 ];

/* Matrix of size: 44 x 44 (row major format) */
real_t rk_A[ 1936 ];

/* Column vector of size: 44 */
real_t rk_b[ 44 ];

/* Column vector of size: 22 */
real_t rk_rhsTemp[ 22 ];

/* Matrix of size: 2 x 572 (row major format) */
real_t rk_diffsTemp[ 1144 ];

/* Matrix of size: 22 x 26 (row major format) */
real_t rk_diffsPrev[ 572 ];

/* Matrix of size: 22 x 26 (row major format) */
real_t rk_diffsNew[ 572 ];


} ACADOworkspace;


/* GLOBAL FORWARD DECLARATIONS:          */
/* ------------------------------------- */
void integrate( real_t* rk_eta );
void solve_dim44_system( real_t* A, real_t* b );
void solve_dim44_triangular( real_t* A, real_t* b );
void solve_dim44_system_reuse( real_t* A, real_t* b );
void acado_rhs( real_t*, real_t* );
void acado_diffs( real_t*, real_t* );
/* ------------------------------------- */


/* EXTERN DECLARATIONS:                  */
/* ------------------------------------- */
extern ACADOworkspace acadoWorkspace;
extern ACADOvariables acadoVariables;
/* ------------------------------------- */
#endif

/* END OF FILE. */

