/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#ifndef SOLVER_QPOASES_H
#define SOLVER_QPOASES_H

#include <stdio.h>
#include <math.h>


#define QPOASES_NVMAX      24
#define QPOASES_NCMAX      24
#define QPOASES_NWSRMAX    144
#define QPOASES_PRINTLEVEL PL_NONE
#define QPOASES_EPS        2.221e-16

typedef double real_t;

typedef struct Params_t {
/* Matrix of size: 24 x 24 (row major format) */
real_t H[ 576 ];

/* Matrix of size: 24 x 24 (row major format) */
real_t A[ 576 ];

/* Row vector of size: 24 */
real_t g[ 24 ];

/* Row vector of size: 24 */
real_t lb[ 24 ];

/* Row vector of size: 24 */
real_t ub[ 24 ];

/* Row vector of size: 24 */
real_t lbA[ 24 ];

/* Row vector of size: 24 */
real_t ubA[ 24 ];

} Params;

typedef struct Vars_t {
/* Row vector of size: 24 */
real_t x[ 24 ];

/* Row vector of size: 48 */
real_t y[ 48 ];

} Vars;

extern Params params;
extern Vars vars;

long solve(void);

#endif
