/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/time.h>

#ifndef ACADO_H
#define ACADO_H

#ifndef __MATLAB__
#ifdef __cplusplus
extern "C"
{
#endif
#endif
#include "qpoases/solver.hpp"


/* COMMON DEFINITIONS:              */
/* -------------------------------- */


/* Number of control intervals */
#define ACADO_N   25
/* Number of differential states */
#define ACADO_NX  8
/* Number of algebraic states */
#define ACADO_NXA  0
/* Number of controls */
#define ACADO_NU  2
/* Number of parameters */
#define ACADO_NP  0


/* GLOBAL VARIABLES:                */
/* -------------------------------- */
typedef struct ACADOvariables_ {
/* Matrix of size: 26 x 8 (row major format) */
real_t x[ 208 ];

/* Matrix of size: 25 x 2 (row major format) */
real_t u[ 50 ];

/* Matrix of size: 25 x 8 (row major format) */
real_t xRef[ 200 ];

/* Matrix of size: 25 x 2 (row major format) */
real_t uRef[ 50 ];


} ACADOvariables;


/* GLOBAL WORKSPACE:                */
/* -------------------------------- */
typedef struct ACADOworkspace_ {
/* Vector of size: 266 */
real_t acado_aux[ 266 ];

real_t rk_ttt;

/* Vector of size: 90 */
real_t rk_xxx[ 90 ];

/* Matrix of size: 4 x 88 (row major format) */
real_t rk_kkk[ 352 ];

int rk_num;

/* Vector of size: 90 */
real_t state[ 90 ];

/* Vector of size: 50 */
real_t g1[ 50 ];

/* Matrix of size: 8 x 50 (row major format) */
real_t H01[ 400 ];

/* Matrix of size: 50 x 50 (row major format) */
real_t H11[ 2500 ];

/* Vector of size: 50 */
real_t lbA[ 50 ];

/* Vector of size: 50 */
real_t ubA[ 50 ];

/* Vector of size: 8 */
real_t deltaX0[ 8 ];

/* Matrix of size: 200 x 8 (row major format) */
real_t C[ 1600 ];

/* Matrix of size: 200 x 8 (row major format) */
real_t QC[ 1600 ];

/* Matrix of size: 8 x 8 (row major format) */
real_t Gx[ 64 ];

/* Matrix of size: 200 x 50 (row major format) */
real_t E[ 10000 ];

/* Matrix of size: 200 x 50 (row major format) */
real_t QE[ 10000 ];

/* Matrix of size: 8 x 2 (row major format) */
real_t Gu[ 16 ];

/* Matrix of size: 25 x 8 (row major format) */
real_t Dx[ 200 ];

/* Vector of size: 200 */
real_t QDx[ 200 ];

/* Matrix of size: 25 x 2 (row major format) */
real_t Du[ 50 ];

/* Matrix of size: 25 x 2 (row major format) */
real_t RDu[ 50 ];


} ACADOworkspace;


/* GLOBAL FORWARD DECLARATIONS:          */
/* ------------------------------------- */
void integrate( real_t* rk_eta );
void acado_rhs_ext( real_t*, real_t* );
void condense1( int index, real_t* yy );
void condense2(  );
void setupQP(  );
void multiplyQC1( real_t* C1, real_t* QC1 );
void multiplyQE1( real_t* E1, real_t* QE1 );
void multiplyQDX1( real_t* Dx1, real_t* QDx1 );
void multiplyRDU1( real_t* Du1, real_t* RDu1 );
void multiplyQC2( real_t* C1, real_t* QC1 );
void multiplyQE2( real_t* E1, real_t* QE1 );
void multiplyQDX2( real_t* Dx1, real_t* QDx1 );
void multiplyC( real_t* Gx, real_t* C1, real_t* C1_new );
void multiplyE( real_t* Gx, real_t* E1, real_t* E1_new );
void multiplyG1( real_t* E, real_t* QDx, real_t* g1 );
void multiplyH01( real_t* C, real_t* QE, real_t* H01 );
void multiplyH11( real_t* E, real_t* QE, real_t* H11 );
real_t getObjectiveValue(  );
void preparationStep(  );
void initialValueEmbedding(  );
int feedbackStep( real_t* x0 );
void shiftControls( real_t* uEnd );
void shiftStates( real_t* xEnd );
real_t getKKT(  );
real_t* getAcadoVariablesX(  );
real_t* getAcadoVariablesU(  );
real_t* getAcadoVariablesXRef(  );
real_t* getAcadoVariablesURef(  );
void printStates(  );
void printControls(  );
real_t getTime(  );
void printHeader(  );
/* ------------------------------------- */


/* EXTERN DECLARATIONS:                  */
/* ------------------------------------- */
extern ACADOworkspace acadoWorkspace;
extern ACADOvariables acadoVariables;
/* ------------------------------------- */
#ifndef __MATLAB__
#ifdef __cplusplus

} // extern "C"
#endif
#endif
#endif

/* END OF FILE. */

