/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008 - 2013 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov and Rien Quirynen.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


#include "acado.h"


void acado_rhs( real_t *acado_x, real_t *acado_f ){
real_t *acado_xd = acado_x;
real_t *acado_u  = acado_x + 8;

/* COMPUTE INTERMEDIATE STATES: */
/* ---------------------------- */
acadoWorkspace.acado_aux[0] = (((real_t)(-78.18237887994039)*acado_xd[1])+((real_t)(3.707267918231886)*acado_xd[6]));
acadoWorkspace.acado_aux[1] = (((real_t)(-40.49371167643454)*acado_xd[3])+((real_t)(1.380322807365873)*acado_xd[7]));

/* COMPUTE OUTPUT: */
/* --------------- */
acado_f[0] = acado_xd[1];
acado_f[1] = acadoWorkspace.acado_aux[0];
acado_f[2] = acado_xd[3];
acado_f[3] = acadoWorkspace.acado_aux[1];
acado_f[4] = acado_xd[5];
acado_f[5] = (((real_t)(1.)/acado_xd[2])*(((((real_t)(-9.81)*(sin(acado_xd[4])))-(acadoWorkspace.acado_aux[0]*(cos(acado_xd[4]))))-(((real_t)(2.)*acado_xd[3])*acado_xd[5]))-((real_t)(0.)/((real_t)(1318.)*acado_xd[2]))));
acado_f[6] = acado_u[0];
acado_f[7] = acado_u[1];
}



void acado_diffs( real_t *acado_x, real_t *acado_f ){
real_t *acado_xd = acado_x;

/* COMPUTE INTERMEDIATE STATES: */
/* ---------------------------- */
acadoWorkspace.acado_aux[0] = (real_t)(0.);
acadoWorkspace.acado_aux[1] = (real_t)(-78.18237887994039);
acadoWorkspace.acado_aux[2] = (real_t)(0.);
acadoWorkspace.acado_aux[3] = (real_t)(0.);
acadoWorkspace.acado_aux[4] = (real_t)(0.);
acadoWorkspace.acado_aux[5] = (real_t)(0.);
acadoWorkspace.acado_aux[6] = (real_t)(3.707267918231886);
acadoWorkspace.acado_aux[7] = (real_t)(0.);
acadoWorkspace.acado_aux[8] = (real_t)(0.);
acadoWorkspace.acado_aux[9] = (real_t)(0.);
acadoWorkspace.acado_aux[10] = (real_t)(0.);
acadoWorkspace.acado_aux[11] = (real_t)(0.);
acadoWorkspace.acado_aux[12] = (real_t)(0.);
acadoWorkspace.acado_aux[13] = (real_t)(-40.49371167643454);
acadoWorkspace.acado_aux[14] = (real_t)(0.);
acadoWorkspace.acado_aux[15] = (real_t)(0.);
acadoWorkspace.acado_aux[16] = (real_t)(0.);
acadoWorkspace.acado_aux[17] = (real_t)(1.380322807365873);
acadoWorkspace.acado_aux[18] = (real_t)(0.);
acadoWorkspace.acado_aux[19] = (real_t)(0.);
acadoWorkspace.acado_aux[20] = (real_t)(-78.18237887994039);
acadoWorkspace.acado_aux[21] = (((real_t)(-78.18237887994039)*acado_xd[1])+((real_t)(3.707267918231886)*acado_xd[6]));
acadoWorkspace.acado_aux[22] = (real_t)(3.707267918231886);

/* COMPUTE OUTPUT: */
/* --------------- */
acado_f[0] = (real_t)(0.);
acado_f[1] = (real_t)(1.);
acado_f[2] = (real_t)(0.);
acado_f[3] = (real_t)(0.);
acado_f[4] = (real_t)(0.);
acado_f[5] = (real_t)(0.);
acado_f[6] = (real_t)(0.);
acado_f[7] = (real_t)(0.);
acado_f[8] = (real_t)(0.);
acado_f[9] = (real_t)(0.);
acado_f[10] = acadoWorkspace.acado_aux[0];
acado_f[11] = acadoWorkspace.acado_aux[1];
acado_f[12] = acadoWorkspace.acado_aux[2];
acado_f[13] = acadoWorkspace.acado_aux[3];
acado_f[14] = acadoWorkspace.acado_aux[4];
acado_f[15] = acadoWorkspace.acado_aux[5];
acado_f[16] = acadoWorkspace.acado_aux[6];
acado_f[17] = acadoWorkspace.acado_aux[7];
acado_f[18] = acadoWorkspace.acado_aux[8];
acado_f[19] = acadoWorkspace.acado_aux[9];
acado_f[20] = (real_t)(0.);
acado_f[21] = (real_t)(0.);
acado_f[22] = (real_t)(0.);
acado_f[23] = (real_t)(1.);
acado_f[24] = (real_t)(0.);
acado_f[25] = (real_t)(0.);
acado_f[26] = (real_t)(0.);
acado_f[27] = (real_t)(0.);
acado_f[28] = (real_t)(0.);
acado_f[29] = (real_t)(0.);
acado_f[30] = acadoWorkspace.acado_aux[10];
acado_f[31] = acadoWorkspace.acado_aux[11];
acado_f[32] = acadoWorkspace.acado_aux[12];
acado_f[33] = acadoWorkspace.acado_aux[13];
acado_f[34] = acadoWorkspace.acado_aux[14];
acado_f[35] = acadoWorkspace.acado_aux[15];
acado_f[36] = acadoWorkspace.acado_aux[16];
acado_f[37] = acadoWorkspace.acado_aux[17];
acado_f[38] = acadoWorkspace.acado_aux[18];
acado_f[39] = acadoWorkspace.acado_aux[19];
acado_f[40] = (real_t)(0.);
acado_f[41] = (real_t)(0.);
acado_f[42] = (real_t)(0.);
acado_f[43] = (real_t)(0.);
acado_f[44] = (real_t)(0.);
acado_f[45] = (real_t)(1.);
acado_f[46] = (real_t)(0.);
acado_f[47] = (real_t)(0.);
acado_f[48] = (real_t)(0.);
acado_f[49] = (real_t)(0.);
acado_f[50] = (real_t)(0.);
acado_f[51] = (((real_t)(1.)/acado_xd[2])*((real_t)(0.)-((cos(acado_xd[4]))*acadoWorkspace.acado_aux[20])));
acado_f[52] = (((((real_t)(0.)-(real_t)(1.))/((acado_xd[2])*(acado_xd[2])))*(((((real_t)(-9.81)*(sin(acado_xd[4])))-(acadoWorkspace.acado_aux[21]*(cos(acado_xd[4]))))-(((real_t)(2.)*acado_xd[3])*acado_xd[5]))-((real_t)(0.)/((real_t)(1318.)*acado_xd[2]))))+(((real_t)(1.)/acado_xd[2])*((real_t)(0.)-((real_t)(0.)-(((real_t)(0.))/(pow(((real_t)(1318.)*acado_xd[2]),2)))))));
acado_f[53] = (((real_t)(1.)/acado_xd[2])*((real_t)(0.)-(acado_xd[5]*(real_t)(2.))));
acado_f[54] = (((real_t)(1.)/acado_xd[2])*(((real_t)(-9.81)*(cos(acado_xd[4])))-(acadoWorkspace.acado_aux[21]*((real_t)(-1.)*(sin(acado_xd[4]))))));
acado_f[55] = (((real_t)(1.)/acado_xd[2])*((real_t)(0.)-((real_t)(2.)*acado_xd[3])));
acado_f[56] = (((real_t)(1.)/acado_xd[2])*((real_t)(0.)-((cos(acado_xd[4]))*acadoWorkspace.acado_aux[22])));
acado_f[57] = (real_t)(0.);
acado_f[58] = (real_t)(0.);
acado_f[59] = (real_t)(0.);
acado_f[60] = (real_t)(0.);
acado_f[61] = (real_t)(0.);
acado_f[62] = (real_t)(0.);
acado_f[63] = (real_t)(0.);
acado_f[64] = (real_t)(0.);
acado_f[65] = (real_t)(0.);
acado_f[66] = (real_t)(0.);
acado_f[67] = (real_t)(0.);
acado_f[68] = (real_t)(1.);
acado_f[69] = (real_t)(0.);
acado_f[70] = (real_t)(0.);
acado_f[71] = (real_t)(0.);
acado_f[72] = (real_t)(0.);
acado_f[73] = (real_t)(0.);
acado_f[74] = (real_t)(0.);
acado_f[75] = (real_t)(0.);
acado_f[76] = (real_t)(0.);
acado_f[77] = (real_t)(0.);
acado_f[78] = (real_t)(0.);
acado_f[79] = (real_t)(1.);
}



/** Column vector of size: 1 */
static const real_t Ah_mat[ 1 ] = { 5.0000000000000001e-03 };


void integrate( real_t* rk_eta )
{
int i;
int j;
int k;
int run;
int run1;
int tmp_index1;
int tmp_index2;
int tmp_index3;

acadoWorkspace.rk_ttt = 0.0000000000000000e+00;
acadoWorkspace.rk_xxx[8] = rk_eta[88];
acadoWorkspace.rk_xxx[9] = rk_eta[89];

for (run = 0; run < 1; ++run)
{
acadoWorkspace.rk_ttt += 1.0000000000000000e+00;
if( acadoWorkspace.resetIntegrator ) {
for (i = 0; i < 1; ++i)
{
for (run1 = 0; run1 < 1; ++run1)
{
acadoWorkspace.rk_xxx[0] = rk_eta[0];
acadoWorkspace.rk_xxx[0] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[0];
acadoWorkspace.rk_xxx[1] = rk_eta[1];
acadoWorkspace.rk_xxx[1] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[1];
acadoWorkspace.rk_xxx[2] = rk_eta[2];
acadoWorkspace.rk_xxx[2] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[2];
acadoWorkspace.rk_xxx[3] = rk_eta[3];
acadoWorkspace.rk_xxx[3] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[3];
acadoWorkspace.rk_xxx[4] = rk_eta[4];
acadoWorkspace.rk_xxx[4] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[4];
acadoWorkspace.rk_xxx[5] = rk_eta[5];
acadoWorkspace.rk_xxx[5] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[5];
acadoWorkspace.rk_xxx[6] = rk_eta[6];
acadoWorkspace.rk_xxx[6] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[6];
acadoWorkspace.rk_xxx[7] = rk_eta[7];
acadoWorkspace.rk_xxx[7] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[7];
acado_diffs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 80 ]) );
for (j = 0; j < 8; ++j)
{
tmp_index1 = (run1 * 8) + (j);
acadoWorkspace.rk_A[tmp_index1 * 8] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 1] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 1)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 2] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 2)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 3] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 3)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 4] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 4)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 5] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 5)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 6] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 7] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 7)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 8) + (j)] -= 1.0000000000000000e+00;
}
acado_rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1 * 8] = acadoWorkspace.rk_kkk[run1] - acadoWorkspace.rk_rhsTemp[0];
acadoWorkspace.rk_b[run1 * 8 + 1] = acadoWorkspace.rk_kkk[run1 + 1] - acadoWorkspace.rk_rhsTemp[1];
acadoWorkspace.rk_b[run1 * 8 + 2] = acadoWorkspace.rk_kkk[run1 + 2] - acadoWorkspace.rk_rhsTemp[2];
acadoWorkspace.rk_b[run1 * 8 + 3] = acadoWorkspace.rk_kkk[run1 + 3] - acadoWorkspace.rk_rhsTemp[3];
acadoWorkspace.rk_b[run1 * 8 + 4] = acadoWorkspace.rk_kkk[run1 + 4] - acadoWorkspace.rk_rhsTemp[4];
acadoWorkspace.rk_b[run1 * 8 + 5] = acadoWorkspace.rk_kkk[run1 + 5] - acadoWorkspace.rk_rhsTemp[5];
acadoWorkspace.rk_b[run1 * 8 + 6] = acadoWorkspace.rk_kkk[run1 + 6] - acadoWorkspace.rk_rhsTemp[6];
acadoWorkspace.rk_b[run1 * 8 + 7] = acadoWorkspace.rk_kkk[run1 + 7] - acadoWorkspace.rk_rhsTemp[7];
}
solve_dim8_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b );
for (j = 0; j < 1; ++j)
{
acadoWorkspace.rk_kkk[j] += acadoWorkspace.rk_b[j * 8];
acadoWorkspace.rk_kkk[j + 1] += acadoWorkspace.rk_b[j * 8 + 1];
acadoWorkspace.rk_kkk[j + 2] += acadoWorkspace.rk_b[j * 8 + 2];
acadoWorkspace.rk_kkk[j + 3] += acadoWorkspace.rk_b[j * 8 + 3];
acadoWorkspace.rk_kkk[j + 4] += acadoWorkspace.rk_b[j * 8 + 4];
acadoWorkspace.rk_kkk[j + 5] += acadoWorkspace.rk_b[j * 8 + 5];
acadoWorkspace.rk_kkk[j + 6] += acadoWorkspace.rk_b[j * 8 + 6];
acadoWorkspace.rk_kkk[j + 7] += acadoWorkspace.rk_b[j * 8 + 7];
}
}
}
for (i = 0; i < 3; ++i)
{
for (run1 = 0; run1 < 1; ++run1)
{
acadoWorkspace.rk_xxx[0] = rk_eta[0];
acadoWorkspace.rk_xxx[0] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[0];
acadoWorkspace.rk_xxx[1] = rk_eta[1];
acadoWorkspace.rk_xxx[1] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[1];
acadoWorkspace.rk_xxx[2] = rk_eta[2];
acadoWorkspace.rk_xxx[2] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[2];
acadoWorkspace.rk_xxx[3] = rk_eta[3];
acadoWorkspace.rk_xxx[3] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[3];
acadoWorkspace.rk_xxx[4] = rk_eta[4];
acadoWorkspace.rk_xxx[4] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[4];
acadoWorkspace.rk_xxx[5] = rk_eta[5];
acadoWorkspace.rk_xxx[5] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[5];
acadoWorkspace.rk_xxx[6] = rk_eta[6];
acadoWorkspace.rk_xxx[6] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[6];
acadoWorkspace.rk_xxx[7] = rk_eta[7];
acadoWorkspace.rk_xxx[7] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[7];
acado_rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1 * 8] = acadoWorkspace.rk_kkk[run1] - acadoWorkspace.rk_rhsTemp[0];
acadoWorkspace.rk_b[run1 * 8 + 1] = acadoWorkspace.rk_kkk[run1 + 1] - acadoWorkspace.rk_rhsTemp[1];
acadoWorkspace.rk_b[run1 * 8 + 2] = acadoWorkspace.rk_kkk[run1 + 2] - acadoWorkspace.rk_rhsTemp[2];
acadoWorkspace.rk_b[run1 * 8 + 3] = acadoWorkspace.rk_kkk[run1 + 3] - acadoWorkspace.rk_rhsTemp[3];
acadoWorkspace.rk_b[run1 * 8 + 4] = acadoWorkspace.rk_kkk[run1 + 4] - acadoWorkspace.rk_rhsTemp[4];
acadoWorkspace.rk_b[run1 * 8 + 5] = acadoWorkspace.rk_kkk[run1 + 5] - acadoWorkspace.rk_rhsTemp[5];
acadoWorkspace.rk_b[run1 * 8 + 6] = acadoWorkspace.rk_kkk[run1 + 6] - acadoWorkspace.rk_rhsTemp[6];
acadoWorkspace.rk_b[run1 * 8 + 7] = acadoWorkspace.rk_kkk[run1 + 7] - acadoWorkspace.rk_rhsTemp[7];
}
solve_dim8_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b );
for (j = 0; j < 1; ++j)
{
acadoWorkspace.rk_kkk[j] += acadoWorkspace.rk_b[j * 8];
acadoWorkspace.rk_kkk[j + 1] += acadoWorkspace.rk_b[j * 8 + 1];
acadoWorkspace.rk_kkk[j + 2] += acadoWorkspace.rk_b[j * 8 + 2];
acadoWorkspace.rk_kkk[j + 3] += acadoWorkspace.rk_b[j * 8 + 3];
acadoWorkspace.rk_kkk[j + 4] += acadoWorkspace.rk_b[j * 8 + 4];
acadoWorkspace.rk_kkk[j + 5] += acadoWorkspace.rk_b[j * 8 + 5];
acadoWorkspace.rk_kkk[j + 6] += acadoWorkspace.rk_b[j * 8 + 6];
acadoWorkspace.rk_kkk[j + 7] += acadoWorkspace.rk_b[j * 8 + 7];
}
}
for (run1 = 0; run1 < 1; ++run1)
{
acadoWorkspace.rk_xxx[0] = rk_eta[0];
acadoWorkspace.rk_xxx[0] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[0];
acadoWorkspace.rk_xxx[1] = rk_eta[1];
acadoWorkspace.rk_xxx[1] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[1];
acadoWorkspace.rk_xxx[2] = rk_eta[2];
acadoWorkspace.rk_xxx[2] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[2];
acadoWorkspace.rk_xxx[3] = rk_eta[3];
acadoWorkspace.rk_xxx[3] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[3];
acadoWorkspace.rk_xxx[4] = rk_eta[4];
acadoWorkspace.rk_xxx[4] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[4];
acadoWorkspace.rk_xxx[5] = rk_eta[5];
acadoWorkspace.rk_xxx[5] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[5];
acadoWorkspace.rk_xxx[6] = rk_eta[6];
acadoWorkspace.rk_xxx[6] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[6];
acadoWorkspace.rk_xxx[7] = rk_eta[7];
acadoWorkspace.rk_xxx[7] += + Ah_mat[run1]*acadoWorkspace.rk_kkk[7];
acado_diffs( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 80 ]) );
for (j = 0; j < 8; ++j)
{
tmp_index1 = (run1 * 8) + (j);
acadoWorkspace.rk_A[tmp_index1 * 8] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 1] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 1)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 2] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 2)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 3] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 3)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 4] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 4)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 5] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 5)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 6] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 8 + 7] = + Ah_mat[run1]*acadoWorkspace.rk_diffsTemp2[(run1 * 80) + (j * 10 + 7)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 8) + (j)] -= 1.0000000000000000e+00;
}
}
for (run1 = 0; run1 < 8; ++run1)
{
for (i = 0; i < 1; ++i)
{
acadoWorkspace.rk_b[i * 8] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1)];
acadoWorkspace.rk_b[i * 8 + 1] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 10)];
acadoWorkspace.rk_b[i * 8 + 2] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 20)];
acadoWorkspace.rk_b[i * 8 + 3] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 30)];
acadoWorkspace.rk_b[i * 8 + 4] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 40)];
acadoWorkspace.rk_b[i * 8 + 5] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 50)];
acadoWorkspace.rk_b[i * 8 + 6] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 60)];
acadoWorkspace.rk_b[i * 8 + 7] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (run1 + 70)];
}
if( 0 == run1 ) {
solve_dim8_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b );
}
 else {
solve_dim8_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b );
}
for (i = 0; i < 1; ++i)
{
acadoWorkspace.rk_diffK[i] = acadoWorkspace.rk_b[i * 8];
acadoWorkspace.rk_diffK[i + 1] = acadoWorkspace.rk_b[i * 8 + 1];
acadoWorkspace.rk_diffK[i + 2] = acadoWorkspace.rk_b[i * 8 + 2];
acadoWorkspace.rk_diffK[i + 3] = acadoWorkspace.rk_b[i * 8 + 3];
acadoWorkspace.rk_diffK[i + 4] = acadoWorkspace.rk_b[i * 8 + 4];
acadoWorkspace.rk_diffK[i + 5] = acadoWorkspace.rk_b[i * 8 + 5];
acadoWorkspace.rk_diffK[i + 6] = acadoWorkspace.rk_b[i * 8 + 6];
acadoWorkspace.rk_diffK[i + 7] = acadoWorkspace.rk_b[i * 8 + 7];
}
for (i = 0; i < 8; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1)] = (i == run1-0);
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1)] += + acadoWorkspace.rk_diffK[i]*(real_t)1.0000000000000000e-02;
}
}
for (run1 = 0; run1 < 2; ++run1)
{
for (i = 0; i < 1; ++i)
{
for (j = 0; j < 8; ++j)
{
tmp_index1 = (i * 8) + (j);
tmp_index2 = (run1) + (j * 10);
acadoWorkspace.rk_b[tmp_index1] = - acadoWorkspace.rk_diffsTemp2[(i * 80) + (tmp_index2 + 8)];
}
}
solve_dim8_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b );
for (i = 0; i < 1; ++i)
{
acadoWorkspace.rk_diffK[i] = acadoWorkspace.rk_b[i * 8];
acadoWorkspace.rk_diffK[i + 1] = acadoWorkspace.rk_b[i * 8 + 1];
acadoWorkspace.rk_diffK[i + 2] = acadoWorkspace.rk_b[i * 8 + 2];
acadoWorkspace.rk_diffK[i + 3] = acadoWorkspace.rk_b[i * 8 + 3];
acadoWorkspace.rk_diffK[i + 4] = acadoWorkspace.rk_b[i * 8 + 4];
acadoWorkspace.rk_diffK[i + 5] = acadoWorkspace.rk_b[i * 8 + 5];
acadoWorkspace.rk_diffK[i + 6] = acadoWorkspace.rk_b[i * 8 + 6];
acadoWorkspace.rk_diffK[i + 7] = acadoWorkspace.rk_b[i * 8 + 7];
}
for (i = 0; i < 8; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 10) + (run1 + 8)] = + acadoWorkspace.rk_diffK[i]*(real_t)1.0000000000000000e-02;
}
}
rk_eta[0] += + acadoWorkspace.rk_kkk[0]*(real_t)1.0000000000000000e-02;
rk_eta[1] += + acadoWorkspace.rk_kkk[1]*(real_t)1.0000000000000000e-02;
rk_eta[2] += + acadoWorkspace.rk_kkk[2]*(real_t)1.0000000000000000e-02;
rk_eta[3] += + acadoWorkspace.rk_kkk[3]*(real_t)1.0000000000000000e-02;
rk_eta[4] += + acadoWorkspace.rk_kkk[4]*(real_t)1.0000000000000000e-02;
rk_eta[5] += + acadoWorkspace.rk_kkk[5]*(real_t)1.0000000000000000e-02;
rk_eta[6] += + acadoWorkspace.rk_kkk[6]*(real_t)1.0000000000000000e-02;
rk_eta[7] += + acadoWorkspace.rk_kkk[7]*(real_t)1.0000000000000000e-02;
for (i = 0; i < 8; ++i)
{
for (j = 0; j < 8; ++j)
{
tmp_index2 = (j) + (i * 8);
rk_eta[tmp_index2 + 8] = acadoWorkspace.rk_diffsNew2[(i * 10) + (j)];
}
for (j = 0; j < 2; ++j)
{
tmp_index2 = (j) + (i * 2);
rk_eta[tmp_index2 + 72] = acadoWorkspace.rk_diffsNew2[(i * 10) + (j + 8)];
}
}
acadoWorkspace.resetIntegrator = 0;
}
for (i = 0; i < 8; ++i)
{
}
}



void solve_dim8_system( real_t* A, real_t* b )
{
int i;
int j;
int k;

int indexMax;

real_t valueMax;

real_t temp;

for (i = 0; i < 8; ++i)
{
acadoWorkspace.rk_dim8_perm[i] = i;
}
for( i=0; i < (7); i++ ) {
	indexMax = i;
	valueMax = fabs(A[i*8+i]);
	for( j=(i+1); j < 8; j++ ) {
		temp = fabs(A[j*8+i]);
		if( temp > valueMax ) {
			indexMax = j;
			valueMax = temp;
		}
	}
	if( indexMax > i ) {
for (k = 0; k < 8; ++k)
{
	acadoWorkspace.rk_dim8_swap = A[i*8+k];
	A[i*8+k] = A[indexMax*8+k];
	A[indexMax*8+k] = acadoWorkspace.rk_dim8_swap;
}
	acadoWorkspace.rk_dim8_swap = b[i];
	b[i] = b[indexMax];
	b[indexMax] = acadoWorkspace.rk_dim8_swap;
	acadoWorkspace.rk_dim8_swap = acadoWorkspace.rk_dim8_perm[i];
	acadoWorkspace.rk_dim8_perm[i] = acadoWorkspace.rk_dim8_perm[indexMax];
	acadoWorkspace.rk_dim8_perm[indexMax] = acadoWorkspace.rk_dim8_swap;
	}
	for( j=i+1; j < 8; j++ ) {
		A[j*8+i] = -A[j*8+i]/A[i*8+i];
		for( k=i+1; k < 8; k++ ) {
			A[j*8+k] += A[j*8+i] * A[i*8+k];
		}
		b[j] += A[j*8+i] * b[i];
	}
}
solve_dim8_triangular( A, b );
}



void solve_dim8_system_reuse( real_t* A, real_t* b )
{

acadoWorkspace.rk_dim8_bPerm[0] = b[acadoWorkspace.rk_dim8_perm[0]];
acadoWorkspace.rk_dim8_bPerm[1] = b[acadoWorkspace.rk_dim8_perm[1]];
acadoWorkspace.rk_dim8_bPerm[2] = b[acadoWorkspace.rk_dim8_perm[2]];
acadoWorkspace.rk_dim8_bPerm[3] = b[acadoWorkspace.rk_dim8_perm[3]];
acadoWorkspace.rk_dim8_bPerm[4] = b[acadoWorkspace.rk_dim8_perm[4]];
acadoWorkspace.rk_dim8_bPerm[5] = b[acadoWorkspace.rk_dim8_perm[5]];
acadoWorkspace.rk_dim8_bPerm[6] = b[acadoWorkspace.rk_dim8_perm[6]];
acadoWorkspace.rk_dim8_bPerm[7] = b[acadoWorkspace.rk_dim8_perm[7]];
acadoWorkspace.rk_dim8_bPerm[1] += A[8]*acadoWorkspace.rk_dim8_bPerm[0];

acadoWorkspace.rk_dim8_bPerm[2] += A[16]*acadoWorkspace.rk_dim8_bPerm[0];
acadoWorkspace.rk_dim8_bPerm[2] += A[17]*acadoWorkspace.rk_dim8_bPerm[1];

acadoWorkspace.rk_dim8_bPerm[3] += A[24]*acadoWorkspace.rk_dim8_bPerm[0];
acadoWorkspace.rk_dim8_bPerm[3] += A[25]*acadoWorkspace.rk_dim8_bPerm[1];
acadoWorkspace.rk_dim8_bPerm[3] += A[26]*acadoWorkspace.rk_dim8_bPerm[2];

acadoWorkspace.rk_dim8_bPerm[4] += A[32]*acadoWorkspace.rk_dim8_bPerm[0];
acadoWorkspace.rk_dim8_bPerm[4] += A[33]*acadoWorkspace.rk_dim8_bPerm[1];
acadoWorkspace.rk_dim8_bPerm[4] += A[34]*acadoWorkspace.rk_dim8_bPerm[2];
acadoWorkspace.rk_dim8_bPerm[4] += A[35]*acadoWorkspace.rk_dim8_bPerm[3];

acadoWorkspace.rk_dim8_bPerm[5] += A[40]*acadoWorkspace.rk_dim8_bPerm[0];
acadoWorkspace.rk_dim8_bPerm[5] += A[41]*acadoWorkspace.rk_dim8_bPerm[1];
acadoWorkspace.rk_dim8_bPerm[5] += A[42]*acadoWorkspace.rk_dim8_bPerm[2];
acadoWorkspace.rk_dim8_bPerm[5] += A[43]*acadoWorkspace.rk_dim8_bPerm[3];
acadoWorkspace.rk_dim8_bPerm[5] += A[44]*acadoWorkspace.rk_dim8_bPerm[4];

acadoWorkspace.rk_dim8_bPerm[6] += A[48]*acadoWorkspace.rk_dim8_bPerm[0];
acadoWorkspace.rk_dim8_bPerm[6] += A[49]*acadoWorkspace.rk_dim8_bPerm[1];
acadoWorkspace.rk_dim8_bPerm[6] += A[50]*acadoWorkspace.rk_dim8_bPerm[2];
acadoWorkspace.rk_dim8_bPerm[6] += A[51]*acadoWorkspace.rk_dim8_bPerm[3];
acadoWorkspace.rk_dim8_bPerm[6] += A[52]*acadoWorkspace.rk_dim8_bPerm[4];
acadoWorkspace.rk_dim8_bPerm[6] += A[53]*acadoWorkspace.rk_dim8_bPerm[5];

acadoWorkspace.rk_dim8_bPerm[7] += A[56]*acadoWorkspace.rk_dim8_bPerm[0];
acadoWorkspace.rk_dim8_bPerm[7] += A[57]*acadoWorkspace.rk_dim8_bPerm[1];
acadoWorkspace.rk_dim8_bPerm[7] += A[58]*acadoWorkspace.rk_dim8_bPerm[2];
acadoWorkspace.rk_dim8_bPerm[7] += A[59]*acadoWorkspace.rk_dim8_bPerm[3];
acadoWorkspace.rk_dim8_bPerm[7] += A[60]*acadoWorkspace.rk_dim8_bPerm[4];
acadoWorkspace.rk_dim8_bPerm[7] += A[61]*acadoWorkspace.rk_dim8_bPerm[5];
acadoWorkspace.rk_dim8_bPerm[7] += A[62]*acadoWorkspace.rk_dim8_bPerm[6];


solve_dim8_triangular( A, acadoWorkspace.rk_dim8_bPerm );
b[0] = acadoWorkspace.rk_dim8_bPerm[0];
b[1] = acadoWorkspace.rk_dim8_bPerm[1];
b[2] = acadoWorkspace.rk_dim8_bPerm[2];
b[3] = acadoWorkspace.rk_dim8_bPerm[3];
b[4] = acadoWorkspace.rk_dim8_bPerm[4];
b[5] = acadoWorkspace.rk_dim8_bPerm[5];
b[6] = acadoWorkspace.rk_dim8_bPerm[6];
b[7] = acadoWorkspace.rk_dim8_bPerm[7];
}

void solve_dim8_triangular( real_t* A, real_t* b )
{

b[7] = b[7]/A[63];
b[6] -= + A[55]*b[7];
b[6] = b[6]/A[54];
b[5] -= + A[47]*b[7];
b[5] -= + A[46]*b[6];
b[5] = b[5]/A[45];
b[4] -= + A[39]*b[7];
b[4] -= + A[38]*b[6];
b[4] -= + A[37]*b[5];
b[4] = b[4]/A[36];
b[3] -= + A[31]*b[7];
b[3] -= + A[30]*b[6];
b[3] -= + A[29]*b[5];
b[3] -= + A[28]*b[4];
b[3] = b[3]/A[27];
b[2] -= + A[23]*b[7];
b[2] -= + A[22]*b[6];
b[2] -= + A[21]*b[5];
b[2] -= + A[20]*b[4];
b[2] -= + A[19]*b[3];
b[2] = b[2]/A[18];
b[1] -= + A[15]*b[7];
b[1] -= + A[14]*b[6];
b[1] -= + A[13]*b[5];
b[1] -= + A[12]*b[4];
b[1] -= + A[11]*b[3];
b[1] -= + A[10]*b[2];
b[1] = b[1]/A[9];
b[0] -= + A[7]*b[7];
b[0] -= + A[6]*b[6];
b[0] -= + A[5]*b[5];
b[0] -= + A[4]*b[4];
b[0] -= + A[3]*b[3];
b[0] -= + A[2]*b[2];
b[0] -= + A[1]*b[1];
b[0] = b[0]/A[0];
}

